name: 'Release Action'
description: 'Creates github releases'
inputs:
  release-files:
    description: 'Directory containing files to attach to the release'
    required: false
  version-file:
    description: 'File containing the current version'
    required: true
    default: "VERSION"
  change-log-file:
    description: 'File containing the change log'
    required: true
    default: "ChangeLog"
  release-prefix:
    description: 'A prefix to add to the release tag. This can be used releases multiple components in the same repo.'
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js'
